### ISSUE TITLE
CLI tool not working

### ISSUE THREAD

**Issue by m4nuC** [decentology/dappstarter-cli#6]
Hi,

I've just tried generating a project from the online version and latest CLI and both seem to fail.

For the CLI case, I get an `Unable to process configuration` error, while on the hosted version the repository URL is wrong (no repository name)

**Comment by jsheely** [comment]
Thank you for the feedback. We did have a few errors today due to some naming conflicts. We are working on a fix and should have an updated out shortly that will remedy your issue. 

I will follow up when complete

**Comment by jsheely** [comment]
This issue should be solved. Please comment if still a problem for you
